# Generated by Django 3.2.7 on 2021-10-03 09:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('cat', models.CharField(choices=[('1', 'hardware'), ('2', 'Laptop'), ('3', 'Computer'), ('4', 'Web Design'), ('5', 'Accessories'), ('6', 'Refurbished'), ('7', 'CCTV'), ('8', 'Repairing')], max_length=1)),
                ('product_name', models.CharField(max_length=500)),
                ('product_price', models.CharField(max_length=100)),
                ('product_image', models.FileField(upload_to='add_images')),
                ('content', ckeditor.fields.RichTextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
